// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUawZSwgbXrj2EH14i9ojw4Ls8xhZu0ns',
    appId: '1:925011142296:web:d352c6d6cce1bb4c1fd2ed',
    messagingSenderId: '925011142296',
    projectId: 'rupeelens-1407',
    authDomain: 'rupeelens-1407.firebaseapp.com',
    databaseURL: 'https://rupeelens-1407-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rupeelens-1407.firebasestorage.app',
    measurementId: 'G-L7LZ5VHFKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJhzlmjLTuqvlfXRGtitA6Gu2I9GyfBGg',
    appId: '1:925011142296:android:6a0214e90d5c6e991fd2ed',
    messagingSenderId: '925011142296',
    projectId: 'rupeelens-1407',
    databaseURL: 'https://rupeelens-1407-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rupeelens-1407.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqjml6yI8jEQ6FPMExap9QKpzF2v6JgyY',
    appId: '1:925011142296:ios:3191bb9440d03f6d1fd2ed',
    messagingSenderId: '925011142296',
    projectId: 'rupeelens-1407',
    databaseURL: 'https://rupeelens-1407-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rupeelens-1407.firebasestorage.app',
    iosBundleId: 'com.sanjay.rupeeLens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqjml6yI8jEQ6FPMExap9QKpzF2v6JgyY',
    appId: '1:925011142296:ios:3191bb9440d03f6d1fd2ed',
    messagingSenderId: '925011142296',
    projectId: 'rupeelens-1407',
    databaseURL: 'https://rupeelens-1407-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rupeelens-1407.firebasestorage.app',
    iosBundleId: 'com.sanjay.rupeeLens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUawZSwgbXrj2EH14i9ojw4Ls8xhZu0ns',
    appId: '1:925011142296:web:8f9c5a1df187417e1fd2ed',
    messagingSenderId: '925011142296',
    projectId: 'rupeelens-1407',
    authDomain: 'rupeelens-1407.firebaseapp.com',
    databaseURL: 'https://rupeelens-1407-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rupeelens-1407.firebasestorage.app',
    measurementId: 'G-B2WFQX1MXY',
  );
}
